Update usatv.yml

diff --git a/.github/workflows/usatv.yml b/.github/workflows/usatv.yml
--- a/.github/workflows/usatv.yml
+++ b/.github/workflows/usatv.yml
@@ -1,13 +1,18 @@
-name: Fetch USATV Channels M3U8
+name: Fetch USATV
 
 on:
   schedule:
     - cron: '0 16 * * *'  # This runs at 12:00 AM PHT (UTC+8)
   workflow_dispatch: # Allows manual trigger from the Actions tab
 
+env:
+  ch_filename: usatv-channels.m3u8
+
 jobs:
   fetch_m3u8_job:
     runs-on: ubuntu-latest
+    env:
+      TZ: Asia/Manila
 
     steps:
       - name: Checkout repository
@@ -15,25 +20,26 @@ jobs:
         with:
           fetch-depth: 1
 
-      - name: Download USATV M3U8 file
+      - name: Download M3U8 files
         run: |
-          curl -fSL "https://usatv.steinxborg.workers.dev/" -o usatv.m3u8
+          echo "Downloading M3U8 files"
+          curl -fSL "${{ secrets.USATV_CH }}" -o "${{ env.ch_filename }}"
 
-      - name: Log the downloaded file details
+      - name: Log the downloaded M3U8 file details
         run: |
-          if [ -f "usatv.m3u8" ]; then
-            echo "M3U8 file downloaded successfully."
-            ls -lh usatv.m3u8
+          if [ -f "${{ env.ch_filename }}" ]; then
+            echo "${{ env.ch_filename }} downloaded successfully."
+            ls -lh "${{ env.ch_filename }}"
           else
-            echo "Failed to download the M3U8 file."
+            echo "Failed to download ${{ env.ch_filename }}."
           fi
 
-      - name: Commit and push the M3U8 file (Squash Commit)
+      - name: Commit and push the M3U8 files (Squash Commit)
         run: |
           git config --global user.name "actions-user"
           git config --global user.email "actions@github.com"
-          git add usatv.m3u8
-          git commit -m "Update M3U8 file" || echo "No changes to commit"
+          git add "${{ env.ch_filename }}"
+          git commit -m "Update M3U8 files" || echo "No changes to commit"
           git push --force-with-lease
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
